name: flutter_gl_web
description: Web platform implementation of flutter_gl, cross-platform call OpenGL API by Dart through dart:ffi. Provides OpenGL with Texture Widget on Flutter. 
homepage: https://github.com/wasabia/flutter_gl
version: 0.0.5

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterGlPlugin
        fileName: flutter_gl_web.dart

dependencies:  
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_gl_platform_interface: ^0.0.4
 
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
